inputs:
- branch: master
  path: .tekton
  type: git
  service: ${githubconsolidated00}
properties: []
triggers: []
#triggers:
#- branch: master
#  eventListener: BUILD
#  name: Git Trigger
#  type: git
#  url: https://github.com/powellquiring/toolchaingittrigger.git
